services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://vidyam.co.in/api/}
    ports:
      - "9966:80"
    restart: always
