services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:6699/api/}
    ports:
      - "6666:80"
    restart: always
