server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Explicit XML headers for sitemap
    location = /sitemap.xml {
        default_type application/xml;
        access_log off;
        try_files $uri =404;
    }

    # Explicit text headers for robots.txt
    location = /robots.txt {
        default_type text/plain;
        access_log off;
        try_files $uri =404;
    }

    # Explicit JSON headers for Web App Manifest
    location = /manifest.json {
        default_type application/json;
        access_log off;
        try_files $uri =404;
    }

    # SPA Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
